version: "3.9"

services:
  j-frontend:
    image: j-frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=500
    volumes:
      - ./j-frontend:/app
      - node_modules_docker:/app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  node_modules_docker:
