services:
  # ---------- 前端 ----------
  j-frontend:
    image: j-frontend
    container_name: j-frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=500
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./j-frontend:/app
      - node_modules_frontend:/app/node_modules
    depends_on:
      - j-api
    networks:
      - app-network

  # ---------- 後端 ----------
  j-api:
    build: ./j-api
    container_name: j-api
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@j-mysql:3306/j_studio
      - NODE_ENV=development
    volumes:
      - ./j-api:/app
      - node_modules_backend:/app/node_modules
    depends_on:
      - j-mysql
    networks:
      - app-network

  # ---------- 資料庫 ----------
  j-mysql:
    image: mysql:8.0
    container_name: j-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=j_studio
      - TZ=Asia/Taipei
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

# ---------- 共用設定 ----------

volumes:
  node_modules_frontend:
  node_modules_backend:
  mysql_data:

networks:
  app-network:
    driver: bridge
